modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/nadia8666/utm/issues/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/nadia8666/utm/"
logoFile="utm_icon.png"
credits=""
authors="nadiarr, rblxpikmin"
description='''
all the small things.

utility & compat mod between various mods (see deps.)
automatically updates from github, disablable in config (though, if working with servers I wouldn't recommend it.
'''

[[mixins]]
config="utm.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.218,)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


#[features.${mod_id}]
#openGLVersion="[3.2,)"

# CREATE
[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.9,6.1.0)"
ordering="AFTER"
side="BOTH"

# EMI
[[dependencies.${mod_id}]]
modId="emi"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"


# SOPHISTICATED BACKPACKS
[[dependencies.${mod_id}]]
modId="sophisticatedbackpacks"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# SPEARS
[[dependencies.${mod_id}]]
modId="spears"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# SHOWCASE ITEM
[[dependencies.${mod_id}]]
modId="showcaseitem"
type="required"
versionRange=","
ordering="AFTER"
side="BOTH"

# FIGURA
[[dependencies.${mod_id}]]
modId="figura"
type="optional"
versionRange=","
ordering="AFTER"
side="CLIENT"

# GRAVESTONES
[[dependencies.${mod_id}]]
modId="gravestone"
type="optional"
versionRange=","
ordering="AFTER"
side="BOTH"

# EXTREME SOUND MUFFLER
[[dependencies.${mod_id}]]
modId="extremesoundmuffler"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"

# GRIMBLE MOD
[[dependencies.${mod_id}]]
modId="grimble_mod"
type="required"
versionRange=","
ordering="AFTER"
side="CLIENT"