
modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="utm_updater" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name} updater" #mandatory
authors="nadiarr"

# The description text for the mod (multi line!) (#mandatory)
description='''
updating your life
'''

[[mixins]]
config="utm_updater.mixins.json"

# UTM
[[dependencies.utm_updater]]
modId="utm"
type="required"
versionRange="[${mod_version}]"
ordering="BEFORE"
side="BOTH"